src/blog/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	event_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^create/', post_create, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
	url(r'^events$', event_list, name='event_list'),
	url(r'^posts$', post_list, name='list'),
]

src/hounds/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
import places.views
import contact.views
from blog.views import HomeView
from allauth.account import views
from axes.decorators import watch_login

urlpatterns = [
	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include("blog.urls", namespace='posts')),
	url(r'^events/', include("places.urls", namespace='events')),
	url(r'^about/', include("about.urls", namespace='about')),
	url(r'^contact/', contact.views.contact, name='contact'),
	url(r'^fetch/$', places.views.fetch_near, name='fetch_near'),
	url(r"^login/$", watch_login(views.login), name="account_login"),	
	url(r'^accounts/', include('allauth.urls')),
	url(r'^ajax/event_create/$', places.views.event_create_modal, name='ajax_event_create'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/places/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	# events_list,
	happyhour_list,
	specials_list,
	EventsUpdateView,
	EventsDeleteView,
	place_list,
	place_create,
	place_detail,
	place_update,
	place_delete,
	neighborhood_list,
	# neighborhood_detail,
	NeighborhoodCreateView,
	NeighborhoodUpdateView,
	NeighborhoodDeleteView,
	Special_typeListView,
	Special_typeCreateView,
	Special_typeUpdateView,
	SpecialtypeDeleteView,
	)

urlpatterns = [
	url(r'^happy_hours$', happyhour_list, name='happyhour_list'),
	url(r'^daily_specials$', specials_list, name='specials_list'),

	url(r'^special_types/$', Special_typeListView.as_view(), name='special_type_list'),
	url(r'^special_types/create/$', Special_typeCreateView.as_view(), name='special_type_create'),
	url(r'^special_types/(?P<pk>\d+)/update/$', Special_typeUpdateView.as_view(), name='special_type_update'),
	url(r'^special_types/(?P<pk>\d+)/delete/$', SpecialtypeDeleteView.as_view(), name='special_type_delete'),	


	url(r'^neighborhood_list/$', neighborhood_list, name='neighborhood_list'),
	url(r'^neighborhood_list/create/$', NeighborhoodCreateView.as_view(), name='neighborhood_create'),
	url(r'^neighborhood_list/(?P<pk>\d+)/edit/$', NeighborhoodUpdateView.as_view(), name='neighborhood_update'),
	url(r'^neighborhood_list/(?P<pk>\d+)/delete/$', NeighborhoodDeleteView.as_view(), name='neighborhood_delete'),

	url(r'^place_list$', place_list, name='place_list'),
	url(r'^place/create$', place_create, name='place_create'),	
	url(r'^(?P<slug>[\w-]+)/$', place_detail, name='place_detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', place_update, name='place_update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', place_delete, name='place_delete'),	
	
	url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/edit/$', EventsUpdateView.as_view(), name='events_update'),
	url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/delete/$', EventsDeleteView.as_view(), name='events_delete'),
	

]

src/places/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from markdown_deux import markdown
# Create your models here.

class EventManager(models.Manager):


	def featured(self, *args, **kwargs):
		return super(EventManager, self).filter(featured=True)

	def sponsored(self, *args, **kwargs):
		return super(EventManager, self).filter(sponsored=True)

	def hour(self, *args, **kwargs):
		return super(EventManager, self).filter(happy_hour=True)

	def special(self, *args, **kwargs):
		return super(EventManager, self).filter(special=True)


class PlaceManager(models.Manager):
	def happy_hour(self):
		return super(PlaceManager, self).filter(event__happy_hour=True)

	def special(self):
		return super(PlaceManager, self).filter(event__special=True)	


def upload_location(instance, filename):
	PlaceModel = instance.__class__
	new_id = PlaceModel.objects.order_by("id").last().id + 1
	"""
	instance.__class__ gets the model Post. We must use this method because the model is defined below.
	Then create a queryset ordered by the "id"s of each object, 
	Then we get the last object in the queryset with `.last()`
	Which will give us the most recently created Model instance
	We add 1 to it, so we get what should be the same id as the the post we are creating.
	"""
	return "%s/%s" %(new_id, filename)

class Neighborhood(models.Model):
	name = models.CharField(max_length=120)
	
	class Meta:
		ordering = ['name']
	
	def __unicode__(self):
		return str(self.name)
		
class Place(models.Model):
	name = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location, 
		null=True, 
		blank=True, 
		width_field="width_field", 
		height_field="height_field")
	height_field = models.IntegerField(default=0, null=True, blank=True)
	width_field = models.IntegerField(default=0, null=True, blank=True)
	alt_text = models.CharField(max_length=255, null=True, blank=True)	
	address = models.CharField(max_length=120)
	neighborhood = models.ForeignKey(Neighborhood, blank=True, null=True, on_delete=models.CASCADE)	
	description = models.TextField(max_length = 255, blank=True, null=True)
	content = models.TextField(blank=True, null=True)
	
	class Meta:
		ordering = ['name']
	
	objects = PlaceManager()
	
	def __unicode__(self):
		return str(self.name)
	
	def get_absolute_url(self):
		return reverse("events:place_detail", kwargs={"slug": self.slug})
	
	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)
	
	def get_description(self):
		description = self.description
		markdown_text = markdown(description)
		return mark_safe(markdown_text)

def create_slug(instance, new_slug=None):
	slug = slugify(instance.name)
	if new_slug is not None:
		slug = new_slug
	qs = Place.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug


def pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(pre_save_receiver, sender=Place)
	
class Day(models.Model):
	day_of_week = models.CharField(max_length = 9)
	day_numbr = models.IntegerField()

	def __unicode__(self):
		return (self.day_of_week)

	
class Special_type(models.Model):
	special_type = models.CharField(max_length = 40 )
	notes = models.TextField(max_length = 255, blank=True, null=True)

	class Meta:
		ordering = ['special_type']
	
	def __unicode__(self):
		return (self.special_type)

class Event(models.Model):
	name = models.CharField(max_length = 40)
	location = models.ForeignKey(Place, on_delete=models.CASCADE)
	special_type = models.ForeignKey(Special_type, blank=True, null=True, on_delete=models.CASCADE)
	happy_hour = models.BooleanField(default=False)
	special = models.BooleanField(default=False)
	featured = models.BooleanField(default=False)
	sponsored = models.BooleanField(default=False)   
	day = models.ManyToManyField(Day)
	time_start = models.TimeField(blank=True, null=True)
	time_end = models.TimeField(blank=True, null=True)
	description = models.TextField(max_length = 255, blank=True, null=True)
	
	objects = EventManager()

	def get_markdown(self):
		description = self.description
		markdown_text = markdown(description)
		return mark_safe(markdown_text)

	def __unicode__(self):
		return (self.name)

	def get_absolute_url(self):
		return reverse("events:events_detail", kwargs={"pk": self.pk})

src/places/forms.py
from django import forms
from datetime import date, datetime, time
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget
from .models import Event, Neighborhood, Place, Special_type
from pagedown.widgets import PagedownWidget

def today():
	today = date.today().weekday()
	return today

now = datetime.now().time().isoformat()


DISTANCES = (
	(1, "1"),
	(2, "2"),
	(5, "5"),
	(10, "10"),
	(15, "15"),
	(20, "20"),    
)

DAYS = (
	("", "-----"),
	(0, "Monday"),
	(1, "Tuesday"),
	(2, "Wednesday"),
	(3, "Thursday"),
	(4, "Friday"),
	(5, "Saturday"),
	(6, "Sunday"),
)

TIME = (
	(now, "----"),
	("01:00", "1:00 AM"),
	("02:00", "2:00 AM"),
	("03:00", "3:00 AM"),
	("04:00", "4:00 AM"),
	("05:00", "5:00 AM"),     
	("06:00", "6:00 AM"),
	("07:00", "7:00 AM"),
	("08:00", "8:00 AM"),
	("09:00", "9:00 AM"),
	("10:00", "10:00 AM"),
	("11:00", "11:00 AM"),
	("12:00", "12:00 PM"),     
	("13:00", "1:00 PM"),
	("14:00", "2:00 PM"),
	("15:00", "3:00 PM"),
	("16:00", "4:00 PM"),
	("17:00", "5:00 PM"),
	("18:00", "6:00 PM"),     
	("19:00", "7:00 PM"),
	("20:00", "8:00 PM"),
	("21:00", "9:00 PM"),
	("22:00", "10:00 PM"),
	("23:00", "11:00 PM"),
	("00:00", "12:00 AM"),     
)




class FetchForm(forms.Form):
	search = forms.CharField(
		required=True,
		widget=forms.TextInput(attrs={'required': 'true'}),
	)
	start_time = forms.TimeField(widget=forms.Select(choices=TIME))
	end_time = forms.TimeField(widget=forms.Select(choices=TIME))
	day = forms.IntegerField(widget=forms.Select(choices=DAYS), initial=today,
								  max_value=10)
	distance = forms.IntegerField(widget=forms.Select(choices=DISTANCES), initial=2,
								  max_value=10)
	

class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		fields = [
			"name",
			"description",
			"location",
			"featured",
			"sponsored",
			"special_type",
			"happy_hour",
			"special",
			"day",
			"time_start",
			"time_end",
		]
		widgets = {
			'time_start': TimeWidget(attrs={'class':'datepicker'}, usel10n = True, bootstrap_version=3),
			'time_end': TimeWidget(attrs={'class':'datepicker'}, usel10n = True, bootstrap_version=3),
		}
		
class PlaceForm(forms.ModelForm):
	content = forms.CharField(required=False, widget=PagedownWidget(show_preview=False))
	class Meta:
		model = Place
		fields = [
			"name",
			"content",
			"description",
			"address",
			"neighborhood",
			"image",

		]

class NeighborhoodForm(forms.ModelForm):
	class Meta:
		model = Neighborhood
		fields = [
			"name",

		]
class Special_typeForm(forms.ModelForm):
	class Meta:
		model = Special_type
		fields = [
			"special_type",
			"notes",

		]

src/templates/places/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>Confirm Delete</h1>
    
    <form method="POST" action="."> {% csrf_token %}
            <p>Are you sure you want to delete: "{{ object }}"?</p>
            <input type='submit' value='Confirm' class='btn btn-warning'>
            <a href='{{ place.get_absolute_url }}' class='btn btn-default'>Cancel</a>
    
    </form>
    
    
</div>

{% endblock %}

src/templates/places/events_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}

{% endblock head_extra %}

{% block content %}
<div class='col-sm-6'>
<h1>Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Create New Object</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Save' />
</form>
</div>

{% endblock content %}
{% block jquery %}

$(".content-markdown").each(function(){
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
})
$(".post-detail-item img").each(function(){
        $(this).addClass("img-responsive")
})


var titleItem = $("#id_name");
$("#preview-title").text(titleItem.val())

var contentInput = $("#id_content");

function setContent(value){
    var markedContent = marked(value)
    $("#preview-content").html(markedContent)
    $("#preview-content img").each(function(){
        $(this).addClass("img-responsive")  
    })
}
setContent(contentInput.val())

contentInput.keyup(function() {
    var newContent = $(this).val()
    setContent(newContent)
})

var titleInput = $("#id_name");

function setTitle(value) {
    $("#preview-title").text(value)
}
setTitle(titleInput.val())

titleInput.keyup(function(){
    var newContent = $(this).val()
    setTitle(newContent)
})
{% endblock %}

src/templates/places/happyhour_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
<form method='GET' action=''>
    <div class='input-group'>
        <input class='form-control' type='text' name='q' placeholder='Search Daily Specials' value='{{ request.GET.q }}'/>
        <span class='input-group-btn'>
        <input class='btn btn-default' type='submit' value='Search' />
        </span>
    </div>
</form>
{% for obj in object_list %}
    <div class="row">
      <div class="col-sm-12">
        <div class="thumbnail">
            {% if obj.image %}
             <img src='{{ obj.image.url }}' alt='{{ obj.alt_text }}' class='img-responsive' />
            {% endif %}
          <div class="caption">
            {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
            <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a></h3>
            <p>{{ obj.get_description|linebreaks|truncatechars:120 }}</p>
            <p><a href="{{ obj.get_absolute_url }}" class="btn btn-info" role="button">View</a></p>
          </div>
        </div>
      </div>
    <hr/>
    </div>
{% endfor %}

{% for neighborhoods in neighborhood_set %}
{% if neighborhoods.place_set.count > 0 %}
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true"> 
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="{{ neighborhoods.name }}">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ neighborhoods.id }}" aria-expanded="false" aria-controls="{{ neighborhoods.id }}">
                {{ neighborhoods.name }}
              </a>
            </h4>
          </div>             
          <div id="{{ neighborhoods.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{ neighborhoods.name }}">

              <div class="panel-body">
                {% for place in neighborhoods.place_set.all %}
				{% if not place.draft %}
                <div class="thumbnail">
                    {% if place.image %}
                     <img src='{{ place.image.url }}' alt='{{ place.alt_text }}' class='img-responsive' />
                    {% endif %}
                  <div class="caption">
                    <h3><a href='{{ place.get_absolute_url }}'>{{ place.name }}</a></h3>
                    <p>{{ place.get_description|linebreaks|truncatechars:120 }}</p>
                    <p><a href="{{ place.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
                  </div>
                </div>
				{% endif %}
                {% endfor %}
                
                
              </div>
          </div>
        </div>
        
    </div>
{% endif %}	
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div> 
</div>

{% endblock content %}

src/templates/places/neighborhood_list.html
{% extends "base.html" %}
{% block content %}
</br>
<p><a type="button" class="btn btn-lg btn-info" href="{% url 'events:neighborhood_create' %}">Add New Neighborhoods</a></p>
<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
<form method='GET' action=''>
    <div class='input-group'>
        <input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
        <span class='input-group-btn'>
        <input class='btn btn-default' type='submit' value='Search' />
        </span>
    </div>
</form>
{% for obj in object_list %}
<div class="row">
    <div class="col-sm-9">
        <h3><a href="{% url 'events:neighborhood_update' pk=obj.pk %}">{{ obj.name }}</a></h3>
    </div>
    <div class="col-sm-3">
        <a type="button" class="btn btn-sm btn-danger" href="{% url 'events:neighborhood_delete' pk=obj.pk %}">Delete Neighborhood</a>
    </div>
  </div>
<hr/>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>


</div>

{% endblock content %}

src/templates/places/place_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}
{{ instance.name }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
{% if request.user.is_staff or request.user.is_superuser %}
<div class="row">
  </br>
  <div class='col-sm-3'>
  <h4>{{ instance.address|linebreaks }}</h4>	
  </div>
  <div class='col-lg-6'>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Add Happy Hour or Special</button>
  <a type="button" class="btn btn-sm btn-info" href="{% url 'events:place_update' slug=instance.slug %}">Edit Location</a>
  </div>
  <div class='col-sm-3'>
  <a type="button" class="btn btn-sm btn-danger" href="{% url 'events:place_delete' slug=instance.slug %}">Delete Location</a>
	<div class="modal fade bs-example-modal-lg" id="EventModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
	  <div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form id ='sendForm' method='POST' action='{% url "ajax_event_create"  %}' enctype='multipart/form-data'>{% csrf_token %}
			<p id='modalMessage'></p>
	
			{{ form.location.as_hidden }}
			<div class="row">
			  <div class='col-sm-6'>
			  <h4>{{ form.name|as_crispy_field }}</h4>
			  </div>
			  <div class='col-sm-3'>
			  <h4>{{ form.featured|as_crispy_field }}</h4>
			  <h4>{{ form.sponsored|as_crispy_field }}</h4>
			  </div>
			  <div class='col-sm-3'>
			  <h4>{{ form.happy_hour|as_crispy_field }}</h4>
			  <h4>{{ form.special|as_crispy_field }}</h4>
			  </div>
			</div>
			<div class="row">
			  <div class='col-sm-6'>
			  <h4>{{ form.special_type|as_crispy_field }}</h4>
			  </div>
			  <div class='col-sm-4'>
			  <h4>{{ form.day|as_crispy_field }}</h4>
			  </div>
			</div>
			<div class="row">
			  <div class='col-sm-6'>  
			  <h4>{{ form.time_start|as_crispy_field }}</h4>
			  </div>
			  <div class='col-sm-6'>
			  <h4>{{ form.time_end|as_crispy_field }}</h4>
			  </div>
			</div> 
			<h4>{{ form.description|as_crispy_field }}</h4>
					  
			<input type='submit' class='btn btn-default' value='Save' id='sendEventForm' />
			</form>
		</div>
	  </div>
	</div>

  </div>
</div>
<hr/>
</br>
{% endif %}
<div class='col-sm-10 col-sm-offset-1'>
<div class='row'>
<div class='col-sm-12'>


    {% if instance.image %}
	</br>
    <img src='{{ instance.image.url }}' alt='{{ instance.alt_text }}' class='img-responsive' />
    {% endif %}
<h1>{{ title }}</h1>	
<div class='content-markdown'>{{ instance.get_description }}</div>
<div class='content-markdown'>{{ instance.get_markdown }}</div>
<hr/>
<br/>
<h1>Happy Hours</h1>
{% for event in instance.event_set.hour %}
<div class="row">
  <div class='col-lg-8'>
  <p id='text-content'><h3>{{ event.get_markdown }}</p></h3>
  <span><p>{{ event.time_start }} -  {{ event.time_end }}</p></span>
  </div>
  {% if request.user.is_staff or request.user.is_superuser %}
  <div class='col-sm-2'>
  <a type="button" class="btn btn-sm btn-default" href="{% url 'events:events_update' slug=instance.slug pk=event.pk %}">Edit Event</a>
  </div>
  <div class='col-sm-2'>
  <a type="button" class="btn btn-sm btn-danger" href="{% url 'events:events_delete' slug=instance.slug pk=event.pk %}">Delete Happy Hour</a>
  </div>
  {% endif %}
</div>
{% endfor %}
<hr/>
{% if instance.event_set.special.count > 0 %}
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true"> 
	<div class="panel panel-default">
	  <div class="panel-heading" role="tab" id="headingOne">
		<h4 class="panel-title">
		  <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
			<h4>Specials</h4>
		  </a>
		</h4>
	  </div>             
	  <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
		  <div class="panel-body">
			{% for event in instance.event_set.special %}
			
			<div class="thumbnail">
			  <div class="caption">
				  <h3>{{ event.get_markdown }}</h3>
				  <span><p>{{ event.time_start }} - 	{{ event.time_end }}</p></span>
				{% if request.user.is_staff or request.user.is_superuser %}
				<div class="row">
				  <div class='col-sm-3'>
				  <a type="button" class="btn btn-sm btn-default" href="{% url 'events:events_update' slug=instance.slug pk=event.pk %}">Edit Event</a>
				  </div>
				  <div class='col-sm-3'>
				  <a type="button" class="btn btn-sm btn-danger" href="{% url 'events:events_delete' slug=instance.slug pk=event.pk %}">Delete Happy Hour</a>
				  </div>
				</div>  
				{% endif %}
			  </div>
			</div>
			{% endfor %}             
		  </div>
	  </div>
	</div>
</div>
{% endif %}
</br>
</br>
</br>
</div>
</div>
</div>
<script>
$(document).ready(function(){           
	$("#sendEventForm").click(function(e){
		e.preventDefault()    
		var mForm = $("#sendForm").serialize();
		$.ajax({
			type: "POST",
			url: "{% url 'ajax_event_create'  %}",
			data: mForm,              
			success: function(data){
				console.log(data)
				$("#modalMessage").html("<p>This was Successful</p>")
				   $("#EventModal").modal("hide")
				  location.reload()
			},
			error: function(data){ 
				var obj = data.responseJSON
				console.log(obj)
				$("#modalMessage").html("<p>Please Fill out All Fields!</p>");
			}
		});
			
	});
  });        
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83948604-1', 'auto');
  ga('send', 'pageview');

</script>

{% endblock content %}

{% block jquery %}
$(".content-markdown").each(function(){
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
})
function setContent(value){
    var markedContent = marked(value)
    $("#content-markdown").html(markedContent)
}
{% endblock %}

src/templates/places/special_type_list.html
{% extends "base.html" %}
{% block content %}
</br>
<p><a type="button" class="btn btn-lg btn-info" href="{% url 'events:special_type_create' %}">Add New Special Categories</a></p>
<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
{% for obj in object_list %}
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true"> 
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="{{ obj.special_type }}">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ obj.id }}" aria-expanded="false" aria-controls="{{ obj.id }}">
                {{ obj.special_type }}
              </a>
            </h4>
          </div>             
          <div id="{{ obj.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{ obj.special_type }}">

              <div class="panel-body">
                <div class="thumbnail">
                  <div class="caption">
                    <p>{{ obj.notes }}</p>
                    <div class="row">
                        <div class='col-sm-3'>
                            <a type="button" class="btn btn-sm btn-info" href="{% url 'events:special_type_update' pk=obj.pk %}">Edit</a>
                        </div>
                        <div class='col-sm-3'>
                            <a type="button" class="btn btn-sm btn-danger" href="{% url 'events:special_type_delete' pk=obj.pk %}">Delete Special Type</a>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
    </div>
{% endfor %}





</div>

{% endblock content %}