src/blog/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	event_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^create/', post_create, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
	url(r'^events$', event_list, name='event_list'),
	url(r'^posts$', post_list, name='list'),
]

src/hounds/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
import places.views
import contact.views
from blog.views import HomeView
from allauth.account import views
from axes.decorators import watch_login

urlpatterns = [
	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include("blog.urls", namespace='posts')),
	url(r'^events/', include("places.urls", namespace='events')),
	url(r'^about/', include("about.urls", namespace='about')),
	url(r'^contact/', contact.views.contact, name='contact'),
	url(r'^fetch/$', places.views.fetch_near, name='fetch_near'),
	url(r"^login/$", watch_login(views.login), name="account_login"),	
	url(r'^accounts/', include('allauth.urls')),
	url(r'^ajax/event_create/$', places.views.event_create_modal, name='ajax_event_create'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from markdown_deux import markdown

from .utils import get_read_time

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

    def event(self, *args, **kwargs):
        return super(PostManager, self).filter(event=True)
    
    def post(self, *args, **kwargs):
        return super(PostManager, self).filter(event=False)

def upload_location(instance, filename):
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    alt_text = models.CharField(max_length=255, null=True, blank=True)
    content = models.TextField()
    event = models.BooleanField()    
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]
        
    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)



def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    
    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var



pre_save.connect(pre_save_post_receiver, sender=Post)

src/blog/forms.py
from django import forms
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget
from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "alt_text",
            "draft",
            "publish",
            "event",
        ]
        widgets = {
            'publish': DateWidget(attrs={'class':'datepicker'}, usel10n = True, bootstrap_version=3),
            
        }
        

src/blog/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass
from datetime import date
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import View

from .forms import PostForm
from .models import Post
from places.models import Place, Event

class HomeView(View):
	def get(self, request, *args, **kwargs):
		today = date.today()
		if not request.user.is_staff or not request.user.is_superuser:
			featured = Place.objects.filter(event__featured=True)
			sponsored = Place.objects.filter(event__sponsored=True)
			posts = Post.objects.post().filter(draft=False).order_by("-timestamp")[:3]
			event_posts = Post.objects.event().filter(draft=False).order_by("-timestamp")[:3]			
			events = Event.objects.all().order_by('-pk')[0:3]
			hhours = Place.objects.filter(
					Q(event__happy_hour=True)|
					Q(event__special=True)
					).distinct().order_by('-pk')[0:3]	
		else:
			featured = Place.objects.filter(event__featured=True)
			sponsored = Place.objects.filter(event__sponsored=True)
			posts = Post.objects.post().order_by("-timestamp")[:3]
			event_posts = Post.objects.event().order_by("-timestamp")[:3]			
			events = Event.objects.all().order_by('-pk')[0:3]
			hhours = Place.objects.filter(
					Q(event__happy_hour=True)|
					Q(event__special=True)
					).distinct().order_by('-pk')[0:3]	
			# hhours = Event.objects.hour().order_by('-pk')[0:3]			
		context = {
			"featured": featured,
			"sponsored": sponsored,
			"event_posts": event_posts,			
			"posts": posts,
			"events": events,
			"hhours": hhours,
		}
		return render(request, "home.html", context)

def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
		
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "blog/post_form.html", context)

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)
	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
	}
	return render(request, "blog/post_detail.html", context)

def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.post().filter(draft=False) #.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.post()
	
	query = request.GET.get("q")
	if query:
		queryset_list = Post.objects.post().filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset, 
		"title": "Posts",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "blog/post_list.html", context)

def event_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.event().filter(draft=False) #.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.event()
	
	query = request.GET.get("q")
	if query:
		queryset_list = Post.objects.event().filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset, 
		"title": "Events",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "blog/post_list.html", context)



def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "blog/post_form.html", context)



def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	if request.method =="POST":
		instance.delete()
		messages.success(request, "Successfully deleted")
		return redirect('posts:list')
	context = {
		"object": instance
	}
	return render(request,"blog/confirm_delete.html", context)

src/templates/blog/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>Confirm Delete</h1>
    
    <form method="POST" action="."> {% csrf_token %}
            <p>Are you sure you want to delete: "{{ object.title }}"?</p>
            <input type='submit' value='Confirm' class='btn btn-warning'>
            <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
    
    </form>
    
    
</div>

{% endblock %}

src/templates/blog/event_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
<form method='GET' action=''>
    <div class='input-group'>
        <input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
        <span class='input-group-btn'>
        <input class='btn btn-default' type='submit' value='Search' />
        </span>
    </div>
</form>
{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
        {% if obj.image %}
         <img src='{{ obj.image.url }}' class='img-responsive' />
        {% endif %}
      <div class="caption post-detail-item">
        {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>
        {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %}
        {{ obj.get_markdown|truncatechars_html:140 }}
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-info" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>




</div>

{% endblock content %}

src/templates/blog/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block content %}
{% if request.user.is_staff or request.user.is_superuser %}
</br>
<a type="button" class="btn btn-sm btn-info" href="{% url 'posts:update' slug=instance.slug %}">Edit Post</a>
<a type="button" class="btn btn-sm btn-danger" href="{% url 'posts:delete' slug=instance.slug %}">Delete Post</a>

{% endif %}


<div class='col-sm-10 col-sm-offset-1'>
    {% if instance.image %}
    <img src='{{ instance.image.url }}' alt='{{ instance.alt_text }}' class='img-responsive' />
    {% endif %}
<h1>{{ title }} <small>{% if instance.draft %}<span style='color:red;'>Draft</span> {% endif %}{{ instance.publish }}</small></h1>
<p>Read time: {% if instance.read_time <= 1 %} < 1 Minute {% else %}{{ instance.read_time }} minutes {% endif %}</p>
{% if instance.user.get_full_name %}
<p>Author: {{ instance.user.get_full_name }}</p>
{% endif %}

<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
<a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}"><i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i></a>
<hr/>
</p>

<div class='row'>
<div class='col-sm-12'>

 <div class='content-markdown post-detail-item'>{{ instance.get_markdown }}</div>

<hr/>
<br/>
<!--<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>-->

</div>
</div>
</div>



<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83948604-1', 'auto');
  ga('send', 'pageview');

</script>

{% endblock content %}

{% block jquery %}
$(".content-markdown").each(function(){
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
})
function setContent(value){
    var markedContent = marked(value)
    $("#content-markdown post-detail-item").html(markedContent)
}
{% endblock %}

src/templates/blog/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}

{% endblock head_extra %}

{% block content %}
<div class='col-sm-6'>
<h1>Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Create New Post</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock content %}

{% block jquery %}

$(".content-markdown").each(function(){
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
})
$(".post-detail-item img").each(function(){
        $(this).addClass("img-responsive")
})


var titleItem = $("#id_title");
$("#preview-title").text(titleItem.val())

var contentInput = $("#id_content");

function setContent(value){
    var markedContent = marked(value)
    $("#preview-content").html(markedContent)
    $("#preview-content img").each(function(){
        $(this).addClass("img-responsive")  
    })
}
setContent(contentInput.val())

contentInput.keyup(function() {
    var newContent = $(this).val()
    setContent(newContent)
})

var titleInput = $("#id_title");

function setTitle(value) {
    $("#preview-title").text(value)
}
setTitle(titleInput.val())

titleInput.keyup(function(){
    var newContent = $(this).val()
    setTitle(newContent)
})
{% endblock %}

src/templates/blog/post_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
<form method='GET' action=''>
    <div class='input-group'>
        <input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
        <span class='input-group-btn'>
        <input class='btn btn-default' type='submit' value='Search' />
        </span>
    </div>
</form>
{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
        {% if obj.image %}
         <img src='{{ obj.image.url }}' class='img-responsive' />
        {% endif %}
      <div class="caption post-detail-item">
        {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>
        {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %}
        <div class='content-markdown'>{{ obj.get_markdown|truncatechars_html:140 }}</div>
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-info" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>




</div>

{% endblock content %}


{% block jquery %}
$(".content-markdown").each(function(){
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
})
function setContent(value){
    var markedContent = marked(value)
    $("#content-markdown").html(markedContent)
}
{% endblock %}