src/about/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	about_list,
	about_create,
	about_detail,
	about_update,
	about_delete,
	)

urlpatterns = [
	url(r'^create/', about_create, name='create'),
	url(r'^(?P<pk>\d+)/$', about_detail, name='detail'),
	url(r'^(?P<pk>\d+)/edit/$', about_update, name='update'),
	url(r'^(?P<pk>\d+)/delete/$', about_delete, name='delete'),
	url(r'^$', about_list, name='list'),
]

src/blog/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	event_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^create/', post_create, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
	url(r'^events$', event_list, name='event_list'),
	url(r'^posts$', post_list, name='list'),
]

src/hounds/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
import places.views
import contact.views
from blog.views import HomeView
from allauth.account import views
from axes.decorators import watch_login

urlpatterns = [
	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include("blog.urls", namespace='posts')),
	url(r'^events/', include("places.urls", namespace='events')),
	url(r'^about/', include("about.urls", namespace='about')),
	url(r'^contact/', contact.views.contact, name='contact'),
	url(r'^fetch/$', places.views.fetch_near, name='fetch_near'),
	url(r"^login/$", watch_login(views.login), name="account_login"),	
	url(r'^accounts/', include('allauth.urls')),
	url(r'^ajax/event_create/$', places.views.event_create_modal, name='ajax_event_create'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/about/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe

from markdown_deux import markdown

class AboutManager(models.Manager):
    def align(self, *args, **kwargs):
        return super(AboutManager, self).filter(align=True)

def upload_location(instance, filename):
	AboutModel = instance.__class__
	new_id = AboutModel.objects.order_by("id").last().id + 1
	return "%s/%s" %(new_id, filename)

class Alignment(models.Model):
	alignment = models.CharField(max_length=5)

	def __unicode__(self):
		return self.alignment

	def __str__(self):
		return self.alignment
	
	

class About(models.Model):
	title = models.CharField(max_length=120)
	image = models.ImageField(upload_to=upload_location, 
			null=True, 
			blank=True, 
			width_field="width_field", 
			height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	alt_text = models.CharField(max_length=255, null=True, blank=True)
	content = models.TextField()
	alignment = models.ForeignKey(Alignment, blank=True, null=True, on_delete=models.CASCADE)
	align = models.BooleanField(default=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	objects = AboutManager()

	def get_absolute_url(self):
		return reverse("about:detail", kwargs={"pk": self.pk})

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

		
	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

src/about/forms.py
from django import forms
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget
from pagedown.widgets import PagedownWidget

from .models import About


class AboutForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	class Meta:
		model = About
		fields = [
			"title",
			"content",
			"image",
			"alt_text",
			"align",
		]

src/about/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import View

from .forms import AboutForm
from .models import About

def about_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
		
	form = AboutForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return redirect('about:list')
	context = {
		"form": form,
	}
	return render(request, "about/about_form.html", context)

def about_detail(request, pk=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404    
	instance = get_object_or_404(About, pk=pk)

	context = {
		"title": instance.title,
		"instance": instance,

	}
	return render(request, "about/about_detail.html", context)

def about_list(request):
	queryset = About.objects.all().order_by('pk')
	context = {
		"object_list": queryset,
		"title": "About Us",
	}
	return render(request, "about/about_list.html", context)





def about_update(request, pk=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(About, pk=pk)
	form = AboutForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return redirect('about:list')

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "about/about_form.html", context)



def about_delete(request, pk=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(About, pk=pk)
	if request.method =="POST":
		instance.delete()
		messages.success(request, "Successfully deleted")
		return redirect('about:list')
	context = {
		"object": instance
	}
	return render(request,"about/confirm_delete.html", context)

src/templates/about/about_detail.html
{% extends "base.html" %}

{% block head_title %}
{{ instance.name }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
<a type="button" class="btn btn-sm btn-info" href="{% url 'about:update' pk=instance.pk %}">Edit Section</a>
<a type="button" class="btn btn-sm btn-danger" href="{% url 'about:delete' pk=instance.pk %}">Delete Section</a>
<div class='col-sm-6 col-sm-offset-3'>


<div class='row'>
<div class='col-sm-12'>


{{ instance.title|linebreaks }}
{{ instance.content|linebreaks }}
<hr/>
<br/>

</div>
</div>
</div>


{% endblock content %}

src/templates/about/about_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}

{% endblock head_extra %}

{% block content %}
<div class='col-sm-6'>
<h1>Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Create New Post</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock content %}

{% block jquery %}

$(".content-markdown").each(function(){
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
})
$(".post-detail-item img").each(function(){
        $(this).addClass("img-responsive")
})


var titleItem = $("#id_title");
$("#preview-title").text(titleItem.val())

var contentInput = $("#id_content");

function setContent(value){
    var markedContent = marked(value)
    $("#preview-content").html(markedContent)
    $("#preview-content img").each(function(){
        $(this).addClass("img-responsive")  
    })
}
setContent(contentInput.val())

contentInput.keyup(function() {
    var newContent = $(this).val()
    setContent(newContent)
})

var titleInput = $("#id_title");

function setTitle(value) {
    $("#preview-title").text(value)
}
setTitle(titleInput.val())

titleInput.keyup(function(){
    var newContent = $(this).val()
    setTitle(newContent)
})
{% endblock %}

src/templates/about/about_list.html
{% extends "base.html" %}
{% block content %}
{% if request.user.is_staff or request.user.is_superuser %}
	<p><a type="button" class="btn btn-lg btn-info" href="{% url 'about:create' %}">Add New About Section</a></p>
	<div class='col-sm-12'>
{% endif %}	
<div class='col-sm-12'>
    <h1>{{ title }}</h1>
	{% for obj in object_list %}
		{% if obj.align %}
			<div class="row">
				<div class="col-sm-5">
					{% if obj.image %}
					 <img src='{{ obj.image.url }}' alt='{{ obj.alt_text }}' class='img-responsive' />
					{% endif %}
				</div>
				<div class="col-sm-7">	
				  <div class="caption post-detail-item">
					{% if request.user.is_staff or request.user.is_superuser %}
					<h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a></h3>
					{% else %}
					<h3>{{ obj.title }}</h3>
					{% endif %}
					{{ obj.get_markdown }}
				  </div>
				</div>
			</div>
			</br>
			<hr/>
		{% else %}
			<div class="row">
				<div class="col-sm-7">	
				  <div class="caption post-detail-item">
					{% if request.user.is_staff or request.user.is_superuser %}
					<h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a></h3>
					{% else %}
					<h3>{{ obj.title }}</h3>
					{% endif %}
					{{ obj.get_markdown }}
				  </div>
				</div>
				<div class="col-sm-5">
					{% if obj.image %}
					 <img src='{{ obj.image.url }}' alt='{{ obj.alt_text }}' class='img-responsive' />
					{% endif %}
				</div>
			</div>
			</br>
			<hr/>
		{% endif %}
	{% endfor %}
</div>		
{% endblock content %}

src/templates/about/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>Confirm Delete</h1>
    
    <form method="POST" action="."> {% csrf_token %}
            <p>Are you sure you want to delete: "{{ object.title }}"?</p>
            <input type='submit' value='Confirm' class='btn btn-warning'>
            <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
    
    </form>
    
    
</div>

{% endblock %}