src/blog/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	event_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^create/', post_create, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
	url(r'^events$', event_list, name='event_list'),
	url(r'^posts$', post_list, name='list'),
]

src/hounds/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
import places.views
import contact.views
from blog.views import HomeView
from allauth.account import views
from axes.decorators import watch_login

urlpatterns = [
	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include("blog.urls", namespace='posts')),
	url(r'^events/', include("places.urls", namespace='events')),
	url(r'^about/', include("about.urls", namespace='about')),
	url(r'^contact/', contact.views.contact, name='contact'),
	url(r'^fetch/$', places.views.fetch_near, name='fetch_near'),
	url(r"^login/$", watch_login(views.login), name="account_login"),	
	url(r'^accounts/', include('allauth.urls')),
	url(r'^ajax/event_create/$', places.views.event_create_modal, name='ajax_event_create'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/places/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	# events_list,
	happyhour_list,
	specials_list,
	EventsUpdateView,
	EventsDeleteView,
	place_list,
	place_create,
	place_detail,
	place_update,
	place_delete,
	neighborhood_list,
	# neighborhood_detail,
	NeighborhoodCreateView,
	NeighborhoodUpdateView,
	NeighborhoodDeleteView,
	Special_typeListView,
	Special_typeCreateView,
	Special_typeUpdateView,
	SpecialtypeDeleteView,
	)

urlpatterns = [
	url(r'^happy_hours$', happyhour_list, name='happyhour_list'),
	url(r'^daily_specials$', specials_list, name='specials_list'),

	url(r'^special_types/$', Special_typeListView.as_view(), name='special_type_list'),
	url(r'^special_types/create/$', Special_typeCreateView.as_view(), name='special_type_create'),
	url(r'^special_types/(?P<pk>\d+)/update/$', Special_typeUpdateView.as_view(), name='special_type_update'),
	url(r'^special_types/(?P<pk>\d+)/delete/$', SpecialtypeDeleteView.as_view(), name='special_type_delete'),	


	url(r'^neighborhood_list/$', neighborhood_list, name='neighborhood_list'),
	url(r'^neighborhood_list/create/$', NeighborhoodCreateView.as_view(), name='neighborhood_create'),
	url(r'^neighborhood_list/(?P<pk>\d+)/edit/$', NeighborhoodUpdateView.as_view(), name='neighborhood_update'),
	url(r'^neighborhood_list/(?P<pk>\d+)/delete/$', NeighborhoodDeleteView.as_view(), name='neighborhood_delete'),

	url(r'^place_list$', place_list, name='place_list'),
	url(r'^place/create$', place_create, name='place_create'),	
	url(r'^(?P<slug>[\w-]+)/$', place_detail, name='place_detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', place_update, name='place_update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', place_delete, name='place_delete'),	
	
	url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/edit/$', EventsUpdateView.as_view(), name='events_update'),
	url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/delete/$', EventsDeleteView.as_view(), name='events_delete'),
	

]

src/contact/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Contact(models.Model):
	email = models.EmailField()
	message = models.CharField(max_length=4000)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	
	def __unicode__(self, ):
		return str(self.email)

	def __str__(self, ):
		return self.email

src/contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = [
			"email",
			"message",
		]
		widgets = {
			'message': forms.Textarea(attrs={'cols':120, 'rows':20}),
		}

src/contact/views.py
from django.shortcuts import render, render_to_response, HttpResponseRedirect, RequestContext
from .forms import ContactForm
# Create your views here.

def contact(request):
	
	form = ContactForm(request.POST or None)
	
	if form.is_valid():
		save_form = form.save(commit=False)
		save_form.save()
	
	return render_to_response('contact_form.html',
							  locals(),
							  context_instance=RequestContext(request))

src/templates/base.html
{% include 'javascript.html' %}
{% include 'head_css.html' %}

{% load staticfiles %}
<!--DOCTYPE html -->
<html>
   
<head>
<title>{% block head_title %}Happy Hour Hounds{% endblock head_title %}</title>

<style>
{% block styles %}




{% endblock %}
</style>
{% block head_extra %} {% endblock head_extra %}
</head>

 




  <div id="navbar-border" class="container">
	<div id="header-item">
		<img src="{% static 'img/HappyHourHeader.jpg' %}" alt="Happy Hour Hounds Logo" width=100%/>
	</div>	
    <!-- Static navbar -->
    <nav  class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button id="navbar-toggle" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
			<li id="fetch-box"><a href="{% url 'fetch_near' %}" >Fetch</a></li>
            <li><a href="{% url 'events:happyhour_list' %}">Happy Hours</a></li>           
            <li><a href="{% url 'events:specials_list' %}">Specials</a></li>
            <li><a href="{% url 'posts:event_list' %}">Events</a></li>
             <li><a href="{% url 'posts:list' %}">Blog</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'about:list' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </nav>
	{% if request.user.is_staff or request.user.is_superuser %}
    <nav  class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button id="navbar-toggle" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'posts:create' %}">New Posts</a></li>
            <li><a href="{% url 'events:place_list' %}">Restaurants</a></li>
            <li><a href="{% url 'events:neighborhood_list' %}">Neighborhoods</a></li>
			<li><a href="{% url 'events:special_type_list' %}">Types of Daily Specials</a></li>
			<li><a href="{% url 'account_logout' %}">Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->  
    </nav>
	{% endif %}	
</div>  
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



{% include "messages_display.html" %}
<div id="main" class='container'>
{% block content %}{% endblock %}
</div>


{% block script %}


{% endblock %}

<script>
$(document).ready(function(){
            {% block jquery %}
            {% endblock %}
         });
</script>





  </body>
</html>

src/templates/contact_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Contact Us</h1>

<!--<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}

<input type='submit' class='btn btn-default' value='Send' />
</form>-->
<p><h4>Email us at: socialmedia@happyhourhounds.com</h4></p>
</div>

{% endblock content %}

src/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Create or Edit New Object</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}

<input type='submit' class='btn btn-default' value='Save' />
</form>
</div>

{% endblock content %}

src/templates/head_css.html
{% load staticfiles %}

<!-- Bootstrap core CSS -->
<!--<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">



<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--<link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">-->
<!-- Latest compiled and minified CSS -->


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Custom styles for this template-->
<link href={% static 'css/navbar.css' %} rel="stylesheet">
<link href={% static 'css/carousel.css' %} rel="stylesheet">
<link href={% static 'css/custom.css' %} rel="stylesheet">
<link href={% static 'css/bootstrap-datetimepicker.css' %} rel="stylesheet">
<link href={% static 'css/datetimepicker.css' %} rel="stylesheet">
<link href={% static 'css/datetimepicker.css' %} rel="stylesheet">

src/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}


{% block styles %}


{% endblock %}

{% block content %}
</br>
</br>
</br>
<div class="row">
  <div class="container" >
    <div class="col-md-6 col-lg-6 col-sm-6">
			<div class="jumbotron">
          <div id="jumbotron-text">
          <h2>Find Happy Hours and Specials Happening Now</h2>
          </div>
          </br>
          </br>
          </br>
          <p>
            <a class="btn btn-lg btn-info" href="{% url 'fetch_near' %}" role="button">Go Fetch!</a>
          </p>
      </div>
    </div>

    <!-- Carousel
    ================================================== -->
    <div class="col-md-6 col-lg-6 col-sm-6">
			<div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
									{% if sponsored %}
										{% for sponsored_item in sponsored %}
										  {% if sponsored_item.image %}
												<img src='{{ sponsored_item.image.url }}' alt='{{ sponsored_item.alt_text }}' class='img-responsive'/>
											{% endif %}
											<div class="container" >
													<div class="carousel-caption">
													{% if sponsored_item.draft %}<h3>Staff only: Draft</h3>{% endif %}
													<h1><a href="{{ sponsored_item.get_absolute_url }}">{{ sponsored_item.name }}</a></h1>
													</div>
												</div>	
										{% endfor %}
									{% else %}
									<div class="container" >
                    <h1>Today's hottest Happy Hours</h1>
                    <p>Click Thru to see the best deals we found today!</p>
									</div>
									{% endif %}
              </div>	
          {% if featured.count > 0 %}
            {% for featured_section in featured %}
              <div class="item">
                {% if featured_section.image %}
                <img src='{{ featured_section.image.url }}' alt='{{ featured_section.alt_text }}' class='img-responsive'/>
                {% endif %}
                <div class="container">
                  <div class="carousel-caption">
                    {% if featured_section.draft %}<h3>Staff only: Draft</h3>{% endif %}
                      <h1><a href="{{ featured_section.get_absolute_url }}" role="button">{{ featured_section.name }}</a></h1>
                  </div>
                </div>
              </div> 
            {% endfor %}
          {% endif %}  
        </div>
        <a class="left carousel-control" style="border-radius: 5px" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" style="border-radius: 5px" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div><!-- /.carousel -->
    </div>
  </div> <!-- /container -->
</div>
   
<div class="row marketing">
  <div class="container content-markdown">  
    <div class="col-sm-4">
    {% if hhours.count > 0 %}
	<h3 id="headline" style="text-align: center">Happy Hours and Specials</h3>
      {% for hhours_section in hhours %}
		{% if hhours_section.image %}
		<img src='{{ hhours_section.image.url }}' alt='{{ hhours_section.alt_text }}' class='img-responsive'/>
		{% endif %}	  
          <h4 style="text-align: center; font-weight: bold">{{ hhours_section.name }}</h4>
          {% if hhours_section.draft %}<h5>Staff only: Draft</h5>{% endif %}
          <p>{{ hhours_section.get_description|truncatechars:140 }}</p>
          <p><a type="button" class="btn btn-sm btn-info" href="{{ hhours_section.get_absolute_url }}" >View More</a></p>
      {% endfor %}
    {% endif %}      
    </div>
    
   <div class="col-sm-4" >
    {% if event_posts.count > 0 %}
	<h3 id="headline" style="text-align: center">Events</h3>
      {% for posts in event_posts %}
		{% if posts.image %}
		<img src='{{ posts.image.url }}' alt='{{ posts.alt_text }}' class='img-responsive'/>
		{% endif %}	  
          <p><h4 style="text-align: center; font-weight: bold">{{ posts.title }}</h4><h6>{{ posts.publish }}</h6></p> 
          {% if posts.draft %}<h5>Staff only: Draft</h5>{% endif %} {% if posts_section.publish > today %}<h5>Staff Only: Future Post</h5>{% endif %}
          <p>{{ posts.get_markdown|truncatechars_html:140 }}</p>
          <p><a type="button" class="btn btn-sm btn-info" href="{{ posts.get_absolute_url }}" >View More</a></p>
      {% endfor %}
    {% endif %}      
    </div>	
   <div class="col-sm-4" >
    {% if posts.count > 0 %}
	<h3 id="headline" style="text-align: center">Blog Posts</h3>
      {% for posts_section in posts %}
		{% if posts_section.image %}
		<img src='{{ posts_section.image.url }}' alt='{{ posts_section.alt_text }}' class='img-responsive'/>
		{% endif %}	  
          <p><h4 style="text-align: center; font-weight: bold">{{ posts_section.title }}</h4><h6>{{ posts_section.publish }}</h6></p> 
          {% if posts_section.draft %}<h5>Staff only: Draft</h5>{% endif %} {% if posts_section.publish > today %}<h5>Staff Only: Future Post</h5>{% endif %}
          <p>{{ posts_section.get_markdown|truncatechars_html:140 }}</p>
          <p><a type="button" class="btn btn-sm btn-info" href="{{ posts_section.get_absolute_url }}" >View More</a></p>
      {% endfor %}
    {% endif %}      
    </div>	
	
  </div><!-- /container --> 
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83948604-1', 'auto');
  ga('send', 'pageview');

</script>

{% endblock content %}

src/templates/hound.html
{% extends "base.html" %}
{% load staticfiles %}


{% block script %}


    <script>
        //{% for items in places %}
        //    var lat = {{ items.1 }}
        //    var lng = {{ items.2 }}
        //{% endfor %}
var lat2 = {{ lat2 }};
var lng2 = {{ lng2 }};
var places = [
        {% for items in places %}
        ['{{ items.0 }}', {{ items.1 }}, {{ items.2}}],
        {% endfor %}    
    ];
function initMap() { 
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: lat2, lng: lng2},
      zoom: 13
    });
    var usermarker = new google.maps.Marker({
      position: {lat: lat2, lng: lng2},
      map: map,
      icon: 'https://maps.google.com/mapfiles/ms/icons/blue-dot.png'
    });
    setMarkers(map);     
}
      
function setMarkers(map) { 

        for (var i = 0; i < places.length; i++) {
            var place = places[i];
            var marker = new google.maps.Marker({
              position: {lat: place[1], lng: place[2]},
              map: map,
              title: place[0],
            });
            var contentString = 'title';
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });             
            marker.addListener('click', function() {
                infowindow.setContent(this.title);
                infowindow.open(map, this);
                }); 
        }
  

        
} 
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAm98ue18q9vVx4qDCgFD4MtesEYPfphu4&callback=initMap"
    async defer></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83948604-1', 'auto');
  ga('send', 'pageview');

</script>
 
{% endblock %}

{% block styles %}

#map {
    margin: 0;
    padding: 0;
    height: 400px;
}

{% endblock %}

{% block content %}
<div class="row">
    <div class="container" style= "text-align: center">
        <h1>Search Happy Hours and Specials</h1>
    </div>
</div>
<div class='row'>
    <div class='col-sm-6' style="text-align: center">
    <form method='POST' action='' id='search_form'>{% csrf_token %}
        <h3>Happening Now Near Me</h3>
        </br>
        <input class='btn btn-default' type='submit' value='Go Fetch!'>

    </form>
    <h3>or</h3>
    </br>
    <a class="btn-sm btn-info" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Advanced Search
    </a>
    <div class="collapse" id="collapseExample">
      <div class="well">
        <form method='GET' action='' id='advanced_form'>{% csrf_token %}
        {% if lat2 %}
        <input class='form-control' type='text' name='q' placeholder='Please Enter Address/Location' value='{{ str_address }}' required />
        {% else %}
        <input class='form-control' type='text' name='q' placeholder='Please Enter Address/Location' value='{{ request.GET.q }}' required />
        {% endif %}
        </br>
        <div clss="row">
            <div class="col-sm-6">
                Distance: {{ form.distance }} mi.
            </div>
            <div class="col-sm-6">    
                Weekday: {{ form.day }}
            </div>   
        </div>
        </br>
        </br>
        <div clss="row">
            <div class="col-sm-6">
                Start Time: {{ form.start_time }}
            </div>
            <div class="col-sm-6">
                End Time: {{ form.end_time }}  
            </div>
        </div>
        </br>
        </br>
        <input class='btn btn-info' type='submit' value='Search' />
        </form>
      </div>
    </div>
    </br>
    </br>
    {% if places.count > 0 %}    
    {% for places in places %}
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true"> 
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="{{ neighborhoods.name }}">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ places.4 }}" aria-expanded="false" aria-controls="{{ places.4 }}">
                      {{ places.0 }}
                    </a>
                </h4>
            </div>             
            <div id="{{ places.4 }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{ places.0 }}">
      
                <div class="panel-body">
                    <div class="caption" style="text-align: left">
                      <p>{{ places.3}}</p>
                      <p><a href="{{ places.5 }}" class="btn btn-primary" role="button">View</a></p>
                    </div>
                </div>
            </div>
        </div>        
    </div>
    {% endfor %}
    {% else %}
                <p><h6>If you have trouble finding anything please try our advanced features to check for different times, or make sure your browser has location services turned on. </h6></p>
    {% endif %}
    
    </div>
    <div class='col-sm-6'>
        <div id="map" style="background-color: white"></div>
    </div>
</div>
</br>
</br>
{% endblock %}

{% block jquery %}
window.onload = function(){
    if(navigator.geolocation)
      navigator.geolocation.getCurrentPosition(onSuccess, onError);
};

function onSuccess(location) {
    $lat2 = location.coords.latitude;
    $lng2 = location.coords.longitude;
    $loc_text = location.coords.latitude + ", " + location.coords.longitude;
    console.log($loc_text);
    $('#search_form').append("<input type='hidden' name='lat2' value='" + $lat2 + "'>");
    $('#search_form').append("<input type='hidden' name='lng2' value='" + $lng2 + "'>");
    $('#advanced_form').append("<input type='hidden' name='lat2' value='" + $lat2 + "'>");
    $('#advanced_form').append("<input type='hidden' name='lng2' value='" + $lng2 + "'>");
};

function onError(){
    console.log("Location not allowed");
};

{% endblock %}

src/templates/javascript.html
{% load staticfiles %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<!-- Latest compiled and minified JavaScript -->
<script   src="https://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js"></script>
<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
<script src="https://use.fontawesome.com/530b5b8658.js"></script>


<!--AIzaSyAm98ue18q9vVx4qDCgFD4MtesEYPfphu4-->

src/templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}